/**
 * Content contract for the technology section.
 *
 * Every string here is copied character-for-character from the Figma frames
 * (file WINXFW2nTM7zYwd5dGgm1T, nodes 1748:1155 and 1924:2259/2285/2311/2337 —
 * one frame per layer) — see DESIGN-MAP.md.
 *
 * All coordinates are **frame units**, straight off those frames. The card is
 * hand-placed against its own layer in the stack and the leader line is drawn
 * to a point on that layer, so this geometry is art direction, not layout that
 * could be derived.
 */

export interface TechnologyImage {
  src: string;
  /** Empty string marks the image decorative (see html-semantics.md). */
  alt: string;
  width: number;
  height: number;
}

export interface TechnologyLayer {
  /** The frame's own two-digit numeral. Decorative — the `ol` carries order. */
  index: string;
  title: string;
  body: string;
  icon: TechnologyImage;
  /** Card's top edge, frame units. */
  cardTop: number;
  /**
   * Where the leader line meets the card: its left edge, at this height. The
   * frame puts it on the card's own centre line, which is why it is not simply
   * `cardTop` plus a constant — the cards are two or three lines tall.
   */
  cardSideY: number;
  /**
   * Centre of the square the leader line plants on the layer, as a fraction of
   * the **artwork** — 0,0 its top-left corner, 1,1 its bottom-right.
   *
   * **Fractions, not frame coordinates, because the artwork is no longer the
   * frame's.** These used to be x/y against the 1440-unit canvas, read off the
   * still Figma shipped; the clip that replaced it composes the stack
   * differently, and the canvas is fluid besides, so those numbers pointed at
   * empty lattice. Measured against the clip's own settled composition instead
   * — the frame from which the cards two to five are read — so they hold at any
   * canvas width and stay right if the box is ever resized.
   */
  anchorFx: number;
  anchorFy: number;
}

/**
 * The exploded stack — a scroll-scrubbed frame sequence, drawn on a canvas.
 *
 * **`src` is the poster, not the reel.** The frames themselves are not content:
 * they are 61 (or 41) numbered files under `/assets/technology/stack-frames/`,
 * generated by `.claude/scripts/video/frames.mjs` and addressed by index, so
 * naming them here would be listing a build artifact one row at a time. What
 * the content layer owns is the still that holds the box until they arrive —
 * the same artwork — and the alt text that describes it. See
 * [[decisions-log]] ADR-0046.
 */
export type TechnologyReel = TechnologyImage;

export interface TechnologyContent {
  /** The section's `h2`, one entry per rendered line — the frame breaks it. */
  heading: string[];
  /** One entry per rendered line; the frame breaks after the first sentence. */
  lede: string[];
  stack: TechnologyReel;
  layers: TechnologyLayer[];
}
